### ISSUE TITLE
Opening Crisp, Spectral Compressor or Diopser more than 1 time crashes FL studio.

### ISSUE THREAD

**Issue by 7LightSeconds** [robbert-vdh/nih-plug#107]
Crash logs:

[Crash 2024-01-20_041218.log](https://github.com/robbert-vdh/nih-plug/files/13996488/Crash.2024-01-20_041218.log)
[Crash 2024-01-20_041313.log](https://github.com/robbert-vdh/nih-plug/files/13996491/Crash.2024-01-20_041313.log)
[Crash 2024-01-20_041719.log](https://github.com/robbert-vdh/nih-plug/files/13996492/Crash.2024-01-20_041719.log)

Possible memory leak. Works fine in Reaper, Ableton Live and Bitwig.

**Comment by robbert-vdh** [comment]
This should now (finally, sorry for taking so long with this) be fixed as of 9e2b9cc06eace2f05d430661873202a2154d0f05. 

The underlying issue is an architectural choice in the GUI framework used by these plugins, and there's sadly no satisfactory solution for this. But the plugins should now at least no longer crash when using multiple instances on Windows and macOS!

**Comment by 7LightSeconds** [comment]
Thank you! I will be probably using it more frequently now! Few of the best plugins I actually use currently. Looking forward to more plugins from you if you ever make some!
