### ISSUE TITLE
Spectral Compressor crashing in mixer insert in fl studio

### ISSUE THREAD

**Issue by ain-soph604** [robbert-vdh/nih-plug#125]
I added a bunch of instances of this compressor in several mixer slots. They're still working, but if i click them or add new one it crashes. 
I can disable them and turn them on just fine. This was in the crash report:

Exception: 
External exception E06D7363
Callstack: 
00007FFD875C0000:00007FFD875ECF19: KERNELBASE.dll
00007FFD61610000:00007FFD61616720: VCRUNTIME140.dll
00007FFD13960000:00007FFD13DD355E: Spectral Compressor.vst3
00007FFD13960000:00007FFD13DCDD69: Spectral Compressor.vst3
00007FFD13960000:00007FFD13DCDB5D: Spectral Compressor.vst3
00007FFD13960000:00007FFD13DCD98B: Spectral Compressor.vst3
00007FFD13960000:00007FFD13DCBAE9: Spectral Compressor.vst3
00007FFD13960000:00007FFD13DCD686: Spectral Compressor.vst3
00007FFD13960000:00007FFD13E041C7: Spectral Compressor.vst3
00007FFD13960000:00007FFD13E042A2: Spectral Compressor.vst3
00007FFD13960000:00007FFD13E04168: Spectral Compressor.vst3
00007FFD13960000:00007FFD13A7DDC9: Spectral Compressor.vst3
00007FFD13960000:00007FFD139CE38F: Spectral Compressor.vst3
00007FFD13960000:00007FFD13BB82A7: Spectral Compressor.vst3
00007FFD13960000:00007FFD13B4CF2A: Spectral Compressor.vst3
00007FFD13960000:00007FFD13B43221: Spectral Compressor.vst3
00007FFD13960000:00007FFD13D9D664: Spectral Compressor.vst3
00007FFD88810000:00007FFD8881EF75: USER32.dll
00007FFD88810000:00007FFD8881E9EE: USER32.dll
00007FFD519D0000:00007FFD51A0F0F0: OPENGL32.dll
00007FFD88810000:00007FFD8881EF75: USER32.dll
00007FFD88810000:00007FFD8881E69D: USER32.dll
00000000024A0000:0000000002933B08: _FLEngine_x64.dll
00000000024A0000:0000000002933B78: _FLEngine_x64.dll
00000000024A0000:0000000002934068: _FLEngine_x64.dll
00000000024A0000:0000000003061C31: _FLEngine_x64.dll
00007FFD2C8D0000:00007FFD2CA88553: FLEngine_x64.dll
00007FF7F23C0000:00007FF7F23C3BA7: FL64.exe
00007FF7F23C0000:00007FF7F23C3FCB: FL64.exe
00007FF7F23C0000:00007FF7F23C5247: FL64.exe
00007FFD886C0000:00007FFD886D7344: KERNEL32.DLL
00007FFD89CB0000:00007FFD89D026B1: ntdll.dll

**Comment by robbert-vdh** [comment]
I need to look into this. It's likely related to Baseview's OpenGL handling, but I'll need to install Windows and FL Studio first to investigate this.

**Comment by robbert-vdh** [comment]
I finally had some time to look into this and I diagnosed the issue here: https://github.com/vizia/vizia/blob/34be9184cd98f3d795d1a73eb9bdccd25b250165/crates/vizia_core/src/context/mod.rs#L63-L64

Fixing this will require some more effort though as Vizia (the GUI framework used) makes pretty heavy use of these globals. I hope I can find some time to look into it this way.

**Comment by ain-soph604** [comment]
Thanks for looking into it. It's an amazing tool you made, I highly appreciate you made this and would love to keep on using it.

**Comment by robbert-vdh** [comment]
This should now (finally, sorry for taking so long with this) be fixed as of 9e2b9cc06eace2f05d430661873202a2154d0f05. 

The underlying issue is an architectural choice in the GUI framework used by these plugins, and there's sadly no satisfactory solution for this. But the plugins should now at least no longer crash when using multiple instances on Windows and macOS!
