### ISSUE TITLE
Several plugins are not loading GUI properly

### ISSUE THREAD

**Issue by bomsaun** [robbert-vdh/nih-plug#165]
FL Studio 21 v21.2.3 (Win 10) is struggling while loading GUI of the following plugins:

Crossover
Loudness War Winner
Buffr Glitch
Puberty Emulator
Safety Limiter
Soft Vacuum

I installed, reinstalled and removed all .fst files and nothing got restored. Does this have a solution or a better installing practice?

Thanks!

**Comment by gunitlalala** [comment]
I'm having this issue as well. Only ones I get a GUI for are:
Diopser
Crisp
Spectral Compressor

**Comment by robbert-vdh** [comment]
Those plugins don't have GUIs, since they're simple enough to just use the host's generic UI! FL Studio used to not have that for VST3 plugins for some reason. Have they still not added the same UI they already have for VST2 plugins to VST3 plugins? Maybe they support it for CLAP plugins now, I have not checked yet.

**Comment by bomsaun** [comment]
Well, the thing is that there’s any UI being displayed. When I open the
plugins mentioned I can’t see any knobs, so they’re unusable.

Do you have any idea of how to get the host generic UI available for this
VST3?
