### ISSUE TITLE
[Crash] Plugin crashes when inserting item into Hash Map (process function)

### ISSUE THREAD

**Issue by AlexW00** [robbert-vdh/nih-plug#24]
I defined my Plugin struct like so:

```rs
struct ClockworkPlugin {
    params: Arc<ClockworkPluginParams>,
    active_notes: HashMap<u8, NoteEvent>,
    last_midi_send_timestamp: SystemTime,
}
```

In the process function, I call `on_note_on` when a note on Event is received:

```rs
fn process(
    &mut self,
    _buffer: &mut Buffer,
    _aux: &mut AuxiliaryBuffers,
    context: &mut impl ProcessContext,
) -> ProcessStatus {
    while let Some(event) = context.next_event() {
        match event {
            NoteEvent::NoteOn { .. } => self.on_note_on(event),
            NoteEvent::NoteOff { .. } => self.on_note_off(event),
            _ => (),
        }
    }
    self.on_midi_send_opportunity(context);
    ProcessStatus::Normal
}
```

In on_note_on I am trying to insert the triggered note into the Hash Map:

```rs
fn on_note_on (&mut self, note_event: NoteEvent) {
    if let NoteEvent::NoteOn {note, ..} = note_event {
        self.active_notes.insert(note, note_event);
    }
}
```

When running the plugin, it crashes as soon as it receives MIDI input. By commenting out other parts of the code, I pinned down the crash to the `self.active_notes.insert(note, note_event);` line.

Link to the full code: https://github.com/AlexW00/clockwork/blob/master/src/lib.rs

How to avoid this crash? I already tried wrapping the HashMap in a Mutex, but it still crashes.

**Comment by robbert-vdh** [comment]
You've enabled the `assert_process_allocs` feature and you're allocating on the audio thread. Enabling this feature will cause all audio thread allocations to panic. You should avoid allocating on the audio thread, as allocations may stall the program for an undetermined amount of time. In general you'll want to avoid any operation that doesn't have a known upper runtime limit on audio threads (anything that isn't wait-free, although lock-free algorithms are almost always perfectly fine if there's not a ton of congestion). So that excludes, (de)allocations, file operations, mutexes, and most system calls.
