### ISSUE TITLE
Make skew_factor functions const

### ISSUE THREAD

**Issue by BSFishy** [robbert-vdh/nih-plug#45]
The `skew_factor` functions inside of `FloatRange` are not currently `const`. This means they can't be used when creating `FloatRange`'s in a `const` context, meaning they can't be used for `FloatRange::Reversed`.

Minimum reproduction:

```rust
use nih_plug::prelude::*;
use std::sync::Arc;

static RATIO_RANGE: FloatRange = FloatRange::Skewed {
    min: 0.0,
    max: 1.0,
    factor: FloatRange::skew_factor(-1.0),
};

#[derive(Params)]
struct PluginParams {
    pub param: FloatParam,
}

impl Default for PluginParams {
    fn default() -> Self {
        Self {
            param: FloatParam::new(
                "param",
                1.0,
                FloatRange::Reversed(&RATIO_RANGE),
            )
        }
    }
}
```

**Comment by robbert-vdh** [comment]
I'd like NIH-plug's core features to work on the stable compiler. How do you propose to make them const without [floating point math](https://github.com/rust-lang/rust/issues/57241)? Or do you propose conditionally making them const only on the nighly compiler? That sounds like a bit of a rabbit hole.

**Comment by robbert-vdh** [comment]
You can probably just use functions or closures instead if you want to reuse ranges or create multiple similar parameters.

**Comment by BSFishy** [comment]
As of now, I'm just manually computing the values and putting them in myself, but it would be nice for these utility functions to be available so I don't have to do this.

Opened as a sort of tracking issue for when floating point math is merged into stable

**Comment by robbert-vdh** [comment]
You can just move the ranges to a function. Or create the range once and then clone it. You won't notice any difference at all. A couple additional divisions and exponentiations during the plugin's startup will not show up on a profiler at all. I'll close this since there doesn't seem to be any indication that const floating point math is being stabilized soon (they haven't even decided on what to do when cross compiling yet).
