### ISSUE TITLE
midi_inverter example could not be opened in Ableton Live

### ISSUE THREAD

**Issue by filipforsstrom** [robbert-vdh/nih-plug#50]
On mac when exporting the midi_inverter example with `cargo xtask bundle midi_inverter --release`, Ableton Live finds the vst3 plugin but theres an error when adding it to a track:

> Failed to create the VST3 plug-in "MIDI Inverter"
> The VST3 plug-in could not be opened.

<img width="544" alt="Screenshot 2023-01-11 at 21 45 34" src="https://user-images.githubusercontent.com/83241499/211914478-1c8403e7-0ff9-44f5-8004-e6dc087280f5.png">

Gain and Poly mod synth examples works without any issues.

**Comment by robbert-vdh** [comment]
Any error messages anywhere? I don't have Ableton Live set up anywhere. You could try changing the default number of channels and the `.accepts_bus_layout()` function to use two channels instead of 0. Given the state of Ableton Live's plugin hosting I wouldn't be surprised if it just flatout rejects MIDI-only plugins.

**Comment by filipforsstrom** [comment]
Changing 
```
const DEFAULT_INPUT_CHANNELS: u32 = 0;
const DEFAULT_OUTPUT_CHANNELS: u32 = 0;
```
to
```
const DEFAULT_INPUT_CHANNELS: u32 = 2;
const DEFAULT_OUTPUT_CHANNELS: u32 = 2;
```

solved the issue. Thanks for the super fast response!

**Comment by dimitriaatos** [comment]
This issue is occurring again, nih-plug's api seems to have changed since this issue was opened and the solution isn't relevant anymore. I assume the current way of defining default channels is the following

```rust
    const AUDIO_IO_LAYOUTS: &'static [AudioIOLayout] = &[
        AudioIOLayout {
            main_input_channels: NonZeroU32::new(2),
            main_output_channels: NonZeroU32::new(2),

            aux_input_ports: &[],
            aux_output_ports: &[],

            names: PortNames::const_default(),
        },
        AudioIOLayout {
            main_input_channels: NonZeroU32::new(1),
            main_output_channels: NonZeroU32::new(1),
            ..AudioIOLayout::const_default()
        },
    ];
```

I tried it out, instead of receiving an error the plugin appeared for a split second and Ableton Live crashed.
