### ISSUE TITLE
`nih_plug_vizia` custom cursors don't seem to work

### ISSUE THREAD

**Issue by 223230** [robbert-vdh/nih-plug#65]
I'm having some issues with setting cursor icons through Vizia's `WindowEvent::SetCursor()`. It does work in regular Vizia, but not under `nih_plug_vizia`. Copying the code from [this](https://github.com/vizia/vizia/blob/main/examples/cursor_icon.rs) Vizia example into a new plugin editor and running it, everything displays correctly and without errors. However, none of the labels change the cursor when hovered. I'm on Windows 11, if that helps.

**Behavior in the original example:**

![Vizia standalone screenshot](https://user-images.githubusercontent.com/68156346/226138504-6fe68f69-3e7f-4bc9-90c0-a25301e7765d.png)

**Behavior when used within `nih_plug_vizia`:**

![nih-plug-vizia screenshot](https://user-images.githubusercontent.com/68156346/226138568-84d53979-5acd-41c3-aaed-8830ba4574ac.png)

**Comment by robbert-vdh** [comment]
Baseview and in turn `vizia_baseview` does not support changing mouse curusors. Baseview has had support for it on X11, but Windows and macOS support are still missing. Someone opened a PR for that (https://github.com/RustAudio/baseview/pull/128) but they haven't replied since. After that functionality makes its way into baseview Vizia would need to add support for it too.
