### ISSUE TITLE
[Feature] Supporting Web UI with Tauri

### ISSUE THREAD

**Issue by stexa** [robbert-vdh/nih-plug#72]
Hey, thanks for your great work!
I would love to never touch JUCE again and stick to this framework for audio plugins.
As I was building some Juce Plugins with Web UI using Websockets to connect to the audio process, I was wondering if it would not be way more elegant with Tauri's messaging system in Plugins.
It is just soo much faster to write guis in javascript, that this would be a killer argument for using Rust for plugins.

So have you thought about integrating Tauri as UI Framework or do you see a possibility for this at all?

**Comment by robbert-vdh** [comment]
Some people have tried to use the webview crate with varying levels of success. Tauri would need to be forked since it can't e embedded inside of other applications at the moment. I'll also only merge a solution into the main NIH-plug repo if it works on all platforms and using all DAWs. Tauri and all other off the shelf solutions right now use gtkwebkit on Linux which is not suitable for plugins. So you would need to fork Tauri first and replace the web browser with, say, Servo (which in turn would also require work to be able to be used as an embeddable web browser).

**Comment by stexa** [comment]
Thanks for your answer! Sounds complicated indeed and might not keep up to the wanted performance in the end. Do you think using slint would be easier to integrate?
I guess you don't want to build support for a library that is not fully MIT, but I don't really understand the new royalty free license... Seems like it is now free to modify and use for desktop targets?
Anyways, I guess I should learn iced or vizia in the end ;)

**Comment by stexa** [comment]
Hey!
Just wanted to check if you understand how it should be possible now to use Slint in VSTs.
On their newest blog-post they say that it is possible now to use slint in vst: https://slint.dev/blog/slint-1.2-released

Any chance you are interested in supporting this?

**Comment by robbert-vdh** [comment]
From what I've heard someone handrolled a plugin wrapper and a windowing layer to use Slint in a plugin. But I'm not up to date with all the details. I'll definitely accept a PR for a `nih_plug_slint` package, but I'm not planning on actively doing so myself since I'd prefer to stick with/work a GUI layer with a permissive license (and ideally, one that produces small-ish binaries).
