### ISSUE TITLE
`SysExMessage::Buffer` requires `Default`, limiting buffer size to 32 bytes

### ISSUE THREAD

**Issue by ijijn** [robbert-vdh/nih-plug#73]
Hi there!

Thank you so much for all the hard work that's gone into NIH-plug and its ecosystem.

I'm just wondering about the `Default` requirement on the `SysExMessage::Buffer` type, effectively limiting the size to 32 bytes because of delightful Rust array shenanigans. I removed this bound locally: everything compiles and all of the tests still pass.

This `Default` doesn't seem necessary here, since the buffer is custom-created via calls to `to_buffer`. The code internals clearly don't rely on this bound and making the type more permissive should be strictly non-breaking. For instance, you could still call `Buffer::default()` on smaller buffers as before (if you're not doing something more direct like `[a, b, c, d, ..]), whereas `[0; N]` or similar would make larger arrays doable.

As for the motivation: for my plugin work, I need comparatively huge SysEx buffers (typically 1kB+) to collect incoming notation/articulation/arbitrary text information from the DAW, update this data and add/modify MIDI events in various ways based on the data contained therein. For debug builds I use a human-readable format but switch to a more compact binary representation for release. It's all working phenomenally well so far, especially with VST3, and I would really like to use the official repo instead of my patched version.

If there are no objections, I'd be happy to submit a pull request for this one-liner.

Thanks again,
Iain

**Comment by robbert-vdh** [comment]
The `Default` constraint is indeed no longer necessary, good catch. It was part of an older design where the equivalent of SysExMessage::to_buffer() would fill in existing slice which meant that the caller had to construct that slice first. Fixed in 727b15aa9304918f0098d6be6ac406ea444737d5. Do keep in mind that if you need to accept 1 KiB SysEx events your plugin's memory consumption will grow by a couple megabytes to be able to handle events that large.
