### ISSUE TITLE
VST3 not recognized in Ableton on Mac M1

### ISSUE THREAD

**Issue by goggledefogger** [robbert-vdh/nih-plug#8]
Hi, thank you for making free plugins, I'd like to try them. I found a link from a youtube video and tried to install on my MacBook Pro M1 with Ableton Live 11 and Ableton Live 10 and neither one showed the plugins in Ableton's browser. I followed [Ableton's help instructions](https://help.ableton.com/hc/en-us/articles/115000349184-VST-AU-plug-in-doesn-t-appear-in-Live-s-Browser#h_27ef5a80-ed03-4923-9f54-20fda95bfbd2) and none of them worked, do you know what might be wrong? Thanks

**Comment by robbert-vdh** [comment]
Hi, 

The plugins up on the CI are compiled for x86_64. Does Ableton Live have no way to use those plugins (through Rosetta?). I know the native ARM version of Bitwig Studio can do that using its sandboxing features. I don't have a Mac so I also have no way to test the Mac versions, but they should work fine.

If anyone wants to help set up ARM macOS builds on the CI then that would be very welcome, but I'd rather not overcomplicate things and I also have no way to test this without buying a Mac. Cargo doesn't support [universal binaries](https://github.com/rust-lang/cargo/issues/8875), and there is also no [ARM macOS GitHub Actions runner](https://github.com/actions/runner/issues/805).

If you compile the plugins yourself (you need to install rustup and then run a command in a terminal, there are instructions on each plugin's page) then those should work just fine, but I don't have ARM-native binaries up on the CI right now. Sorry!

**Comment by autumnblazey** [comment]
hmm, I think I might know how to do this, so I may work on it if this is something that is wanted?

**Comment by autumnblazey** [comment]
@goggledefogger you could try to open ableton using rosetta, by right clicking on the application and clicking "get info", and checking the rosetta box before opening it:

<img width="244" alt="image" src="https://user-images.githubusercontent.com/49562048/172038243-20217d3e-7b00-4a02-81c2-47c86f75b8ff.png">

<img width="241" alt="image" src="https://user-images.githubusercontent.com/49562048/172038188-56b66517-31e1-409f-9661-98c6548a50d7.png">

I would also suggest cloning the code and building it on the mac itself, which would build for apple silicon and probably show up in ableton, but I just tried doing that and it has a mistake in the code (will PR a fix in a moment). Also for some reason it doesn't want to bundle it "because the package does not export any plugins", so must try to figure it out >~<

**Comment by robbert-vdh** [comment]
> hmm, I think I might know how to do this, so I may work on it if this is something that is wanted?

@autumnblazey If you know how to set up another [build](https://github.com/robbert-vdh/nih-plug/blob/master/.github/workflows/build.yml) for macOS that compiles to AArch64 macOS from x86_64 macOS (since that's what GitHub's CI runners are running) then that would be great! Rust currently doesn't have a built in way to do universal builds, and I would very much prefer not having to make the `xtask bundle` implementation more complicated by manually approximating that with lipo or something like that. So just having two separate macOS builds would be nice.

> Also for some reason it doesn't want to bundle it "because the package does not export any plugins", so must try to figure it out >~< Some pointers on why this is may be helpful

I'll assume that's a native build on an M1 Mac? No idea, but the answer must be in here:  https://github.com/robbert-vdh/nih-plug/blob/bc2b3410891c2b15c9869bd2f5debee689dc78f2/nih_plug_xtask/src/symbols.rs#L5-L34

That's what NIH-plug's bundler currently uses to check which symbols are exported by a plugin. This works fine on x86_64 macOS, so the only reasonable explanation is that this is either a bug in the used goblin binary parsing library, or the library is somehow a fat multiarch Mach-O binary with the AArch64 version being the second architecture. That would sound very strange, but somehow it also sounds like a very Apple thing to do. You should be able to add a `dbg!(&obj);` before line 19 there to find out.

**Comment by robbert-vdh** [comment]
Oh and the third option would be that the symbol on AArch64 binaries doesn't have the underscore prepended to it. Still don't know why that's a thing. So if the `dbg!(&obj);` doesn't show anything interesting, look through the `obj.exports` to check which symbols are actually exported.

**Comment by robbert-vdh** [comment]
Okay, I added AArch64 builds for macOS @goggledefogger! You can find them separately from the x86_64 builds on both the GitHub Actions pages and on the nightly.link page.

@autumnblazey No idea why it didn't work for you, but the symbol detection worked fine when cross compiling to `aarch64-apple-darwin` on the `macos-11` GitHub CI runner.

**Comment by aponplugins** [comment]
Hi, I'm currently working on M1 macOS and am running into an issue where the `.vst3` files I build from the `plugins/` folder are not showing up in Ableton Live 11, while the plugins downloaded from the nightly builds are working fine. To build, I am running the following:
```
cargo xtask bundle buffr_glitch --target aarch64-apple-darwin --release
```
I also tried running this:
```
cargo xtask bundle-universal buffr_glitch --release
```
but was met with a significant number of compiler errors.

Based on the CI changes here, I would think that the builds should be the same, but maybe I'm missing something.

**Comment by robbert-vdh** [comment]
@aponplugins Not sure why the plugins downloaded from GitHub would be fine (they're also unsigned), but AArch64 macOS seems to be much stricter about code signing and may refuse to run anything that isn't signed. Try running `codesign -f -s - 'target/bundled/plugin-name.vst3'`. Apparently there's an issue where Cargo doesn't always do that for you (it's supposed to). This may have something to do with Live's use of the hardened runtime. This supposedly isn't an issue in other hosts like Bitwig Studio. I'll add this step to the bundler, hopefully that helps.

**Comment by aponplugins** [comment]
That worked perfectly, thanks! Yes I'm not sure why the downloaded versions worked, there aren't any `_CodeSignature` files in them.

Also, FYI, I had to run this:
```
xattr -cr 'target/bundled/plugin-name.vst3'
```
before re-signing the project files. This is because I got this error trying to re-sign:
```
resource fork, Finder information, or similar detritus not allowed
```
I found the solution here:
https://stackoverflow.com/questions/39652867/code-sign-error-in-macos-monterey-xcode-resource-fork-finder-information-or

Based on these responses, maybe my compilation of the executables is creating local resource forks and my OS can't work with that.

**Comment by robbert-vdh** [comment]
Any idea what triggered that to be necessary that? The linked docs talk about a change from macOS Sierra, and I haven't heard about having to use `xattr -cr` before.

**Comment by joelbyrnes** [comment]
I think I might have the answer for you. I'm not a plugin dev (yet?) or even a mac software dev, so maybe this is already well known, but I had the same problem on both intel and m1 macs where the plugins just wouldn't show in any DAW. The above didn't seem to help me because I had two problems. 

The main issue solved above is that macs "quarantine" unknown executables for security, such as those downloaded in browser. With an exe you can just allow it in Security settings, and the same thing appeared for plugins but it didn't do anything. I found in a random reddit post that you can remove it manually like this:

```xattr -rd com.apple.quarantine <vst3 path>```

Which explains why the above `xattr -cr` works, it's just removing all attributes. I guess they're given those attributes as part of the build. So you'll need to do that locally or make it part of your build on mac. 

That worked once I copied them into files in /Library/Audio/Plug-Ins/VST(3) or the ~/Library equivalent. My other problem was I was trying to load them directly from my build folder under ~/src. I guess the DAW doesn't have access to those folders and silently ignored it. So copy them into `~/Library/...` if your DAW supports that. Symlinks may also work. 

With that solved, I can now become an audio plugin dev! Thanks for this great framework!
